### ISSUE TITLE
Coverage task fails silently

### ISSUE THREAD

**Issue by tandrewnichols** [mmoulton/grunt-mocha-cov#36]
This may or may not be an issue with grunt-mocha-cov. Just hoping for some direction in finding the problem really.

I use this library in most of my projects and so far, I haven't had any trouble. In the most recent project (which is actually an old project that I'm updating), `grunt coverage` (which is an alias to `grunt mochacov:html`) fails silently (by which I mean it fails with no explanation of what went wrong). I've had this happen before, but in that case, the problem was that one of the tests was failing, and fixing the test fixed the coverage report. I've already verified that that is not the problem in the case.

I've tried logging the `spawnOptions` in lib/mocha right before `grunt.util.spawn` is called, and I get this in the problem project:

```
{ cmd: '/Users/AndrewNichols/code/anichols/varity/node_modules/grunt-mocha-cov/node_modules/.bin/mocha',
  args: 
   [ '--reporter',
     'html-cov',
     '--ui',
     'mocha-given',
     '--require',
     'coffee-script/register',
     '--require',
     'node_modules/grunt-mocha-cov/lib/instrument',
     'test/acceptance.coffee',
     'test/helpers.coffee',
     'test/index.coffee',
     'test/mixins.coffee',
     'test/operations.coffee',
     'test/varity.coffee' ] }
```

and this in a working project:

```
{ cmd: '/Users/AndrewNichols/code/anichols/manta/kindly/node_modules/grunt-mocha-cov/node_modules/.bin/mocha',
  args: 
   [ '--reporter',
     'html-cov',
     '--ui',
     'mocha-given',
     '--require',
     'coffee-script/register',
     '--require',
     'node_modules/grunt-mocha-cov/lib/instrument',
     'test/acceptance.coffee',
     'test/helpers.coffee',
     'test/kindly.coffee' ] }
```

So basically the same (just different files). Additionally if I manually call mocha exactly as spawn calls it, it works normally and an html coverage file is generated. So, i.e., I run:

`./node_modules/grunt-mocha-cov/node_modules/.bin/mocha --reporter html-cov --ui mocha-given --require coffee-script/register --require node_modules/grunt-mocha-cov/lib/instrument test/acceptance.coffee test/helpers.coffee test/index.coffee test/mixins.coffee test/operations.coffee test/varity.coffee`

and it works fine.

FURTHERMORE, the coverage report actually _is_ generated. If I add `stdio: 'inherit'` to the spawnOptions, the full coverage html file is printed to the console, and I see things like "hits=45" etc.

I've dug into both grunt and mocha to try to find the problem. So far, all I can say definitively is that the process exit code is 11. The error object is not especially useful - it just says "Error". Here's the stack trace, but I'm not expecting that to be helpful, since spawned processes are involved:

```
Error
    at callDone (/Users/AndrewNichols/code/anichols/varity/node_modules/grunt/node_modules/grunt-legacy-util/index.js:159:56)
    at ChildProcess.<anonymous> (/Users/AndrewNichols/code/anichols/varity/node_modules/grunt/node_modules/grunt-legacy-util/index.js:198:5)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Socket.<anonymous> (child_process.js:966:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

Here's the entirety of my Gruntfile:

``` javascript
module.exports = function(grunt) {
  grunt.loadNpmTasks('grunt-contrib-jshint');
  grunt.loadNpmTasks('grunt-mocha-test');
  grunt.loadNpmTasks('grunt-mocha-cov');
  grunt.loadNpmTasks('grunt-travis-matrix');

  grunt.initConfig({
    jshint: {
      options: {
        reporter: require('jshint-stylish'),
        eqeqeq: true,
        es3: true,
        indent: 2,
        newcap: true,
        quotmark: 'single'
      },
      all: ['lib/*.js']
    },
    mochacov: {
      lcov: {
        options: {
          reporter: 'mocha-lcov-reporter',
          instrument: true,
          ui: 'mocha-given',
          require: 'coffee-script/register',
          output: 'coverage/coverage.lcov'
        },
        src: ['test/helpers.coffee', 'test/**/*.coffee'],
      },
      html: {
        options: {
          reporter: 'html-cov',
          ui: 'mocha-given',
          require: 'coffee-script/register',
          output: 'coverage/coverage.html'
        },
        src: ['test/helpers.coffee', 'test/**/*.coffee']
      }
    },
    mochaTest: {
      options: {
        reporter: 'spec',
        ui: 'mocha-given',
        require: 'coffee-script/register'
      },
      test: {
        src: ['test/helpers.coffee', 'test/**/*.coffee']
      }
    },
    travis: {
      options: {
        targets: {
          test: '{{ version }}',
          when: 'v0.10',
          tasks: ['mochacov:lcov', 'matrix:v0.10']
        }
      }
    },
    matrix: {
      'v0.10': 'codeclimate < coverage/coverage.lcov'
    }
  });

  grunt.registerTask('mocha', ['mochaTest:test']);
  grunt.registerTask('default', ['jshint:all', 'mocha']);
  grunt.registerTask('coverage', ['mochacov:html']);
  grunt.registerTask('ci', ['jshint:all', 'mocha', 'travis']);
};
```

and just for comparison, a working Gruntfile:

``` javascript
module.exports = function(grunt) {
  grunt.loadNpmTasks('grunt-contrib-jshint');
  grunt.loadNpmTasks('grunt-mocha-test');
  grunt.loadNpmTasks('grunt-mocha-cov');
  grunt.loadNpmTasks('grunt-travis-matrix');

  grunt.initConfig({
    jshint: {
      options: {
        reporter: require('jshint-stylish'),
        eqeqeq: true,
        es3: true,
        indent: 2,
        newcap: true,
        quotmark: 'single'
      },
      all: ['lib/**/*.js']
    },
    mochacov: {
      lcov: {
        options: {
          reporter: 'mocha-lcov-reporter',
          instrument: true,
          ui: 'mocha-given',
          require: 'coffee-script/register',
          output: 'coverage/coverage.lcov'
        },
        src: ['test/**/*.coffee'],
      },
      html: {
        options: {
          reporter: 'html-cov',
          ui: 'mocha-given',
          require: 'coffee-script/register',
          output: 'coverage/coverage.html'
        },
        src: ['test/**/*.coffee']
      }
    },
    mochaTest: {
      options: {
        reporter: 'spec',
        ui: 'mocha-given',
        require: 'coffee-script/register'
      },
      test: {
        src: ['test/**/*.coffee']
      }
    },
    travis: {
      options: {
        targets: [
          {
            test: '{{ version }}',
            when: 'v0.10',
            tasks: ['mochacov:lcov', 'matrix:v0.10']
          }
        ]
      }
    },
    matrix: {
      'v0.10': 'codeclimate < coverage/coverage.lcov'
    }
  });

  grunt.registerTask('mocha', ['mochaTest:test']);
  grunt.registerTask('default', ['jshint:all', 'mocha']);
  grunt.registerTask('coverage', ['mochacov:html']);
  grunt.registerTask('ci', ['jshint:all', 'mocha', 'travis']);
}
```

I do also have the following defined in my package.json:

``` javascript
  "config": {
    "blanket": {
      "pattern": [
        "varity/lib"
      ]
    }
  }
```

I've looked at the blanket code, and I'm not seeing anything unexpected there. It appears to be matching the correct files.

If you have _any_ insight into this at all, or even an idea of where to look next, that would be super helpful. Thanks.

Sorry for the novel here.

**Comment by openhoat** [comment]
I have the same problem.
Trying to locate the origin of the problem, I found a really strange behaviour :
- first, like you, all my tests are ok with mocha
- most of my tests are using request and promises to test a server (usual use case)

With this code in a 'it', mochacov works :

```
return request({...}).spread(function (res, body) {
  expect(res).to.be.ok;
  expect(res.statusCode).to.be.ok;
});
```

With this last line changed, mochacov fails (error callDone):

```
return request({...}).spread(function (res, body) {
  expect(res).to.have.property('statusCode', 201);
});
```

The res arg is effectively a number and is equal to 201...
I use this snippet of code in hundreds of tests without any problem (in travis also).
It makes me crazy

**Comment by openhoat** [comment]
When excluding one file among a hundred from blanket, the problem disapears :

```
"config": {
    "blanket": {
      "pattern": ["lib"],
      "data-cover-never": [
        "samples",
        "node_modules",
        "test",
        "lib/services/util"
      ]
    }
  }
```

**Comment by openhoat** [comment]
I found the origin of the issue :
Blanket does not like this kind of code :

```
buildUrlPrefix: function (paths) {
    paths = [];
    Array.prototype.slice.call(arguments).forEach(function (path) {...});
}
```

blanket redefine the value of the first argument to [] !
For me it's a bug because paths is a local variable...
