### ISSUE TITLE
running mochacov with generator function not working

### ISSUE THREAD

**Issue by nirmalgupta** [mmoulton/grunt-mocha-cov#42]
Warning: /Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3872
            throw e;
                  ^
Error: Line 27: Unexpected token *
    at throwError (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1156:21)
    at throwUnexpected (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1213:9)
    at parseVariableIdentifier (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:2081:13)
    at /Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseFunctionExpression (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:2967:18)
    at /Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parsePrimaryExpression (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1535:24)
    at /Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at trackLeftHandSideExpressionAllowCall (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3504:61)
    at parsePostfixExpression (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1703:20)
    at /Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseUnaryExpression (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1784:16)
    at /Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseMultiplicativeExpression (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1790:20)
    at /Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseAdditiveExpression (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1807:20)
    at /Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseShiftExpression (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1824:20)
    at /Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseRelationalExpression (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1845:16)
    at /Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseEqualityExpression (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1863:20)
    at /Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseBitwiseANDExpression (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1880:20)
    at /Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseBitwiseXORExpression (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1896:20)
    at /Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseBitwiseORExpression (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1912:20)
    at /Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseLogicalANDExpression (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1930:20)
    at /Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseLogicalORExpression (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1946:20)
    at /Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseConditionalExpression (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1966:16)
    at /Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseAssignmentExpression (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1993:16)
    at /Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseAssignmentExpression (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:2010:24)
    at /Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseExpression (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:2020:20)
    at /Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseStatement (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:2783:16)
    at /Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseSourceElement (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3062:20)
    at parseSourceElements (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3095:29)
    at parseProgram (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3109:19)
    at /Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parse (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3856:23)
    at module.exports (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/falafel/index.js:32:15)
    at Object.blanket._blanket.instrument (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/src/blanket.js:115:37)
    at Object.require.extensions..js (/Users/nirmal/myproject/node_modules/grunt-mocha-cov/node_modules/blanket/src/index.js:148:25)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by nirmalgupta** [comment]
duplicate to #43
